import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1734321309822 implements MigrationInterface {
    name = 'Init1734321309822'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`transfer-branch-status\` (\`status_id\` varchar(255) NOT NULL, \`status_desc\` enum ('Menunggu Proses', 'Menunggu Approval', 'Approval Ditolak', 'Sedang Dikirim', 'Diterima dan Diproses', 'TOB Ditolak', 'TOB Diterima') NOT NULL DEFAULT 'Approval Ditolak', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`status_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`base_entity\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_bast_document\` (\`id\` varchar(36) NOT NULL, \`no_rekening\` varchar(255) NULL, \`bulan_putusan\` varchar(255) NULL, \`tahun_putusan\` varchar(255) NULL, \`doc_id\` varchar(255) NULL, \`doc_name\` varchar(255) NULL, \`number\` varchar(255) NULL, \`date\` varchar(255) NULL, \`bastId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_bast\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`bast_number\` varchar(32) NULL, \`date\` datetime NULL, \`branch_name\` varchar(255) NULL, \`branch_address\` text NULL, \`branch_address_province\` text NULL, \`branch_address_city\` text NULL, \`branch_phone_number\` varchar(50) NULL, \`pihak_pertama_name\` varchar(50) NULL, \`pihak_pertama_pernr\` varchar(10) NULL, \`pihak_pertama_jabatan\` varchar(50) NULL, \`pihak_pertama_uker\` varchar(100) NULL, \`pihak_kedua_name\` varchar(50) NULL, \`pihak_kedua_pernr\` varchar(10) NULL, \`pihak_kedua_jabatan\` varchar(50) NULL, \`pihak_kedua_uker\` varchar(100) NULL, \`additional_desc\` text NULL, \`maker_uker_asal_pernr\` varchar(10) NULL, \`maker_uker_asal_name\` varchar(50) NULL, \`maker_uker_asal_position\` varchar(50) NULL, \`maker_uker_asal_division\` varchar(50) NULL, \`signer_uker_asal_pernr\` varchar(10) NULL, \`signer_uker_asal_name\` varchar(50) NULL, \`signer_uker_asal_position\` varchar(50) NULL, \`signer_uker_asal_division\` varchar(50) NULL, \`maker_uker_tujuan_pernr\` varchar(10) NULL, \`maker_uker_tujuan_name\` varchar(50) NULL, \`maker_uker_tujuan_position\` varchar(50) NULL, \`maker_uker_tujuan_division\` varchar(50) NULL, \`signer_uker_tujuan_pernr\` varchar(10) NULL, \`signer_uker_tujuan_name\` varchar(50) NULL, \`signer_uker_tujuan_position\` varchar(50) NULL, \`signer_uker_tujuan_division\` varchar(50) NULL, \`toboutId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_file\` (\`id\` varchar(36) NOT NULL, \`docId\` varchar(20) NOT NULL, \`docName\` varchar(50) NOT NULL, \`physique\` tinyint NOT NULL DEFAULT 0, \`digital\` tinyint NOT NULL DEFAULT 0, \`physique_tob_in\` tinyint NOT NULL DEFAULT 0, \`digital_tob_in\` tinyint NOT NULL DEFAULT 0, \`decisionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_decision_storage_address\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`kreditLokasi\` varchar(100) NULL, \`kreditRuangan\` varchar(20) NULL, \`kreditLemari\` varchar(20) NULL, \`kreditRak\` varchar(20) NULL, \`kreditBaris\` varchar(20) NULL, \`agunanLokasi\` varchar(100) NULL, \`agunanRuangan\` varchar(20) NULL, \`agunanLemari\` varchar(20) NULL, \`agunanRak\` varchar(20) NULL, \`agunanBaris\` varchar(20) NULL, \`decisionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_decision\` (\`id\` int NOT NULL AUTO_INCREMENT, \`decisionYear\` varchar(4) NOT NULL, \`decisionMonth\` varchar(2) NOT NULL, \`accountNumberId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out_acc\` (\`id\` varchar(36) NOT NULL, \`acctNum\` varchar(20) NOT NULL, \`productType\` varchar(50) NOT NULL, \`productFacility\` varchar(50) NOT NULL, \`toboutId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shift_doc_tob_out\` (\`id\` varchar(36) NOT NULL, \`acctCIF\` varchar(20) NOT NULL, \`acctName\` varchar(50) NOT NULL, \`originBranch\` varchar(70) NOT NULL, \`originName\` varchar(70) NOT NULL, \`destinationBranch\` varchar(70) NOT NULL, \`destinationName\` varchar(70) NOT NULL, \`requestDate\` date NOT NULL, \`aproval_pernr\` varchar(8) NULL, \`aproval_name\` varchar(60) NULL, \`aproval_notes\` text NULL, \`aproval_in_pernr\` varchar(8) NULL, \`aproval_in_name\` varchar(60) NULL, \`aproval_in_notes\` text NULL, \`pengelola_name\` varchar(60) NULL, \`pengelola_pernr\` varchar(8) NULL, \`status\` enum ('Request', 'Submit', 'Di Setujui', 'Di Tolak') NOT NULL DEFAULT 'Request', \`reason\` varchar(300) NOT NULL, \`delivery_type\` enum ('BRI', 'Expedition') NOT NULL DEFAULT 'BRI', \`bri_sender_pernr\` varchar(8) NULL, \`bri_sender_name\` varchar(60) NULL, \`bri_sender_phone_number\` varchar(60) NULL, \`expedition_service\` varchar(20) NULL, \`expedition_receipt\` varchar(50) NULL, \`created_by_pernr\` varchar(8) NULL, \`bast_filename\` varchar(50) NULL, \`is_minio\` tinyint NULL DEFAULT 0, \`bast_path\` text NULL, \`step_tob\` enum ('periksa_dokumen', 'form_bast', 'form_pengiriman', 'konfirmasi') NOT NULL DEFAULT 'periksa_dokumen', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tob_activity_status\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`check_document\` varchar(255) NULL, \`check_document_date\` varchar(255) NULL, \`check_document_name\` varchar(255) NULL, \`check_document_pernr\` varchar(255) NULL, \`approval_out\` varchar(255) NULL, \`approval_out_date\` varchar(255) NULL, \`approval_out_name\` varchar(255) NULL, \`approval_out_pernr\` varchar(255) NULL, \`sending\` varchar(255) NULL, \`sending_date\` varchar(255) NULL, \`sending_name\` varchar(255) NULL, \`sending_pernr\` varchar(255) NULL, \`accept_and_process\` varchar(255) NULL, \`accept_and_process_date\` varchar(255) NULL, \`accept_and_process_name\` varchar(255) NULL, \`accept_and_process_pernr\` varchar(255) NULL, \`approval_in\` varchar(255) NULL, \`approval_in_date\` varchar(255) NULL, \`approval_in_name\` varchar(255) NULL, \`approval_in_pernr\` varchar(255) NULL, \`completed\` varchar(255) NULL, \`completed_date\` varchar(255) NULL, \`toboutId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`log_fetch_branch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`success\` int NOT NULL, \`failed\` int NOT NULL, \`times\` varchar(50) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`log_fetch_branch_duplicate\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cif\` varchar(50) NOT NULL, \`nomorRekening\` varchar(50) NOT NULL, \`branchTujuanKode\` varchar(50) NOT NULL, \`branchAsalKode\` varchar(50) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transfers_of_branches\` (\`id\` int NOT NULL AUTO_INCREMENT, \`cif\` varchar(128) NOT NULL, \`debiturName\` varchar(255) NOT NULL, \`nomorRekening\` varchar(128) NOT NULL, \`branchAsalKode\` varchar(128) NOT NULL, \`branchAsalNama\` varchar(255) NOT NULL, \`branchTujuanKode\` varchar(128) NOT NULL, \`branchTujuanNama\` varchar(255) NOT NULL, \`pengelolaPN\` varchar(255) NOT NULL, \`pengelolaNama\` varchar(255) NOT NULL, \`tglApproveTujuan\` datetime NOT NULL, \`statusTOBKode\` varchar(128) NOT NULL, \`statusTOBDeskripsi\` varchar(255) NOT NULL, \`tglRequestTOB\` datetime NULL, \`tobOutId\` varchar(128) NULL, \`statusTOBProcess\` enum ('Menunggu Proses', 'Menunggu Approval', 'Approval Ditolak', 'Sedang Dikirim', 'Sedang Diproses', 'Diterima dan Diproses', 'TOB Ditolak', 'TOB Diterima') NOT NULL DEFAULT 'Menunggu Proses', \`statusTOBMasuk\` enum ('Menunggu Proses', 'Menunggu Approval', 'Approval Ditolak', 'Sedang Dikirim', 'Diterima dan Diproses', 'TOB Ditolak', 'TOB Diterima') NOT NULL DEFAULT 'Menunggu Proses', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, INDEX \`IDX_88269ad986a145955febdcdb87\` (\`branchAsalKode\`), UNIQUE INDEX \`IDX_fe696c33d4673afe637c71dc7e\` (\`cif\`, \`nomorRekening\`, \`branchAsalKode\`, \`branchTujuanKode\`, \`statusTOBProcess\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_bast_document\` ADD CONSTRAINT \`FK_92bb3d0c5e726a3d8da7bdaf4d1\` FOREIGN KEY (\`bastId\`) REFERENCES \`shift_doc_tob_out_bast\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_bast\` ADD CONSTRAINT \`FK_a6a6c93e30b14ce33b778eee1e7\` FOREIGN KEY (\`toboutId\`) REFERENCES \`shift_doc_tob_out\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_file\` ADD CONSTRAINT \`FK_52c6232a7a29b6894103c99c57a\` FOREIGN KEY (\`decisionId\`) REFERENCES \`shift_doc_tob_out_decision\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_decision_storage_address\` ADD CONSTRAINT \`FK_28250fa8588c48cdc1ed9c2df1b\` FOREIGN KEY (\`decisionId\`) REFERENCES \`shift_doc_tob_out_decision\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_decision\` ADD CONSTRAINT \`FK_e712fc1383256ad1bbea0d1f9df\` FOREIGN KEY (\`accountNumberId\`) REFERENCES \`shift_doc_tob_out_acc\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_acc\` ADD CONSTRAINT \`FK_10bbaa668e5f6ac8c9f76b4ca21\` FOREIGN KEY (\`toboutId\`) REFERENCES \`shift_doc_tob_out\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tob_activity_status\` ADD CONSTRAINT \`FK_2d602b5bcc879b6774e31245cb1\` FOREIGN KEY (\`toboutId\`) REFERENCES \`shift_doc_tob_out\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tob_activity_status\` DROP FOREIGN KEY \`FK_2d602b5bcc879b6774e31245cb1\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_acc\` DROP FOREIGN KEY \`FK_10bbaa668e5f6ac8c9f76b4ca21\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_decision\` DROP FOREIGN KEY \`FK_e712fc1383256ad1bbea0d1f9df\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_decision_storage_address\` DROP FOREIGN KEY \`FK_28250fa8588c48cdc1ed9c2df1b\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_file\` DROP FOREIGN KEY \`FK_52c6232a7a29b6894103c99c57a\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_bast\` DROP FOREIGN KEY \`FK_a6a6c93e30b14ce33b778eee1e7\``);
        await queryRunner.query(`ALTER TABLE \`shift_doc_tob_out_bast_document\` DROP FOREIGN KEY \`FK_92bb3d0c5e726a3d8da7bdaf4d1\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe696c33d4673afe637c71dc7e\` ON \`transfers_of_branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_88269ad986a145955febdcdb87\` ON \`transfers_of_branches\``);
        await queryRunner.query(`DROP TABLE \`transfers_of_branches\``);
        await queryRunner.query(`DROP TABLE \`log_fetch_branch_duplicate\``);
        await queryRunner.query(`DROP TABLE \`log_fetch_branch\``);
        await queryRunner.query(`DROP TABLE \`tob_activity_status\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_acc\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_decision\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_decision_storage_address\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_file\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_bast\``);
        await queryRunner.query(`DROP TABLE \`shift_doc_tob_out_bast_document\``);
        await queryRunner.query(`DROP TABLE \`base_entity\``);
        await queryRunner.query(`DROP TABLE \`transfer-branch-status\``);
    }

}
